[package]
name = "execpool"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
tokio = { version = "1.5.0", features = ["sync", "rt", "macros"] }
ed25519-dalek = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0.1"
log = "0.4.14"
bincode = "1.3.3"
futures = "0.3.14"
async-trait = "0.1.50"

crypto = { path = "../crypto" }
store = { path = "../store" }
network = { path = "../network" }
types = { path = "../types"}

[dev-dependencies]
tokio-util = { version = "0.7.3", features= ["codec"] }
rand = "0.7.3"

[features]
benchmark = []
